name: Build with Gradle

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4
      
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: current

    - name: Build with Gradle
      run: |
        gradle build
        mv app/build/outputs/apk/release/*.apk KernelFlasher.apk

    - name: Upload Release
      uses: actions/upload-artifact@v4
      with:
        name: KernelFlasher
        path: KernelFlasher.apk
